x-db_healthcheck: &db_healthcheck
  healthcheck:
    test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    start_period: 10s
    interval: 10s
    timeout: 5s
    retries: 3

services:

  db:
    image: mariadb:10
    volumes:
      - ./db/certs:/certs:ro
      - ./db/db.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: pwmgr
      MYSQL_USER: idpmgmt
      MYSQL_PASSWORD: idpmgmt
    <<: *db_healthcheck

  testdb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: test
      MYSQL_USER: idpmgmt
      MYSQL_PASSWORD: idpmgmt
    <<: *db_healthcheck

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - "51151:80"
      - "51153:443"
    environment:
      PMA_HOST: db
      PMA_USER: idpmgmt
      PMA_PASSWORD: idpmgmt

  api:
    build: ./
    volumes:
      - ./application:/data
    ports:
      - "51155:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./common.env
      - path: ./local.env
        required: false
      - ./db/certs/test.env

  apitest:
    build: ./
    volumes:
      - ./application:/data
    depends_on:
      testdb:
        condition: service_healthy
      zxcvbn:
        condition: service_started
      broker:
        condition: service_healthy
    env_file:
      - ./common.env
      - ./test.env
    environment:
      MYSQL_HOST: testdb
      MYSQL_DATABASE: test
      APP_ENV: test
      ID_BROKER_baseUrl: http://broker
    command: ["/data/run-tests-api.sh"]

  unittest:
    build: ./
    volumes:
      - ./application:/data
      - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
    depends_on:
      db:
        condition: service_healthy
      zxcvbn:
        condition: service_started
    env_file:
      - ./common.env
      - ./test.env
    environment:
      MYSQL_HOST: testdb
      MYSQL_DATABASE: test
      APP_ENV: test
      ID_BROKER_baseUrl: http://broker
    command: ["/data/run-tests.sh"]

  integrationtest:
    build: ./
    volumes:
      - ./application:/data
      - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
    depends_on:
      testdb:
        condition: service_healthy
      zxcvbn:
        condition: service_started
    env_file:
      - ./common.env
      - ./test.env
      - path: ./local.env
        required: false
    environment:
      MYSQL_HOST: testdb
      MYSQL_DATABASE: test
      APP_ENV: test
      ID_BROKER_baseUrl: http://broker
    command: ["/data/run-tests-integration.sh"]

  cli:
    build: ./
    volumes:
      - ./application:/data
      - composer-cache:/composer
    depends_on:
      testdb:
        condition: service_healthy
    working_dir: /data
    environment:
      COMPOSER_CACHE_DIR: /composer
    env_file:
      - ./common.env
      - path: ./local.env
        required: false
    command: ["true"]

  zxcvbn:
    image: wcjr/zxcvbn-api:1.1.0
    platform: linux/amd64

  brokerDb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker
    <<: *db_healthcheck

  brokerpma:
    image: phpmyadmin:5
    ports:
      - "51158:80"
    environment:
      PMA_HOST: brokerDb
      PMA_USER: broker
      PMA_PASSWORD: broker

  broker:
    image: ghcr.io/sil-org/idp-id-broker:8
    platform: linux/amd64
    ports:
      - "51154:80"
    depends_on:
      brokerDb:
        condition: service_healthy
    volumes:
      - ./dockerbuild/broker/m381901_235959_insert_test_data.php:/app/console/migrations/m381901_235959_insert_test_data.php
      - ./dockerbuild/broker/User.php:/app/console/migrations/User.php
      - ./dockerbuild/broker/Method.php:/app/console/migrations/Method.php
    environment:
      EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      IDP_NAME: idp1
      MYSQL_HOST: brokerDb
      MYSQL_DATABASE: broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker
      API_ACCESS_KEYS: abc123
      HELP_CENTER_URL: https://example.com/#/help
      PASSWORD_FORGOT_URL: https://example.com/#/forgot
      PASSWORD_PROFILE_URL: https://example.com/#/profile
      SUPPORT_EMAIL: support@example.com
      EMAIL_SIGNATURE: Dummy Signature for Tests
      APP_ENV: test
      MFA_TOTP_apiBaseUrl: not_needed_here
      MFA_TOTP_apiKey: not_needed_here
      MFA_TOTP_apiSecret: not_needed_here
      MFA_WEBAUTHN_apiBaseUrl: not_needed_here
      MFA_WEBAUTHN_apiKey: not_needed_here
      MFA_WEBAUTHN_apiSecret: not_needed_here
    healthcheck:
      test: nc -vz localhost 80
      start_period: 1s
      interval: 1s
      timeout: 5s
      retries: 20

  ldap:
    build: ./dockerbuild/ldap
    healthcheck:
      test: nc -vz localhost 389
      start_period: 1s
      interval: 1s
      timeout: 5s
      retries: 90

  ldapload:
    build: ./dockerbuild/ldap
    depends_on:
      ldap:
        condition: service_healthy
    working_dir: /data
    command: ./load_ldap.sh

  raml2html:
    image: mattjtodd/raml2html
    platform: linux/amd64
    volumes:
      - ./api.raml:/api.raml
      - ./api.html:/api.html
    command: -i api.raml -o api.html

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.31.0/24
          gateway: 10.20.31.1

volumes:
  composer-cache:
